Import('RTT_ROOT')
Import('rtconfig')
from building import *

cwd 	= GetCurrentDir()
path	= cwd + '/include'
src		= Glob('*.c')
CPPPATH	= [path, str(Dir('#'))]

group = DefineGroup('devdriver', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
